// <auto-generated />
using System;
using JOB_FINDER_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JOB_FINDER_API.Migrations
{
    [DbContext(typeof(JobFinderDbContext))]
    [Migration("20250623025230_updatenenee1234567")]
    partial class updatenenee1234567
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JOB_FINDER_API.Models.AboutMe", b =>
                {
                    b.Property<int>("AboutMeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutMeId"));

                    b.Property<string>("AboutMeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AboutMeId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("AboutMes");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SimilarityScore")
                        .HasColumnType("real");

                    b.Property<string>("SnapshotCv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Award", b =>
                {
                    b.Property<int>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AwardId"));

                    b.Property<string>("AwardDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwardName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwardOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Month")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("AwardId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullCvJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CandidateProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("CandidateProfiles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Main Street",
                            CandidateProfileId = 0,
                            City = "Ho Chi Minh City",
                            Dob = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            JobTitle = "Software Developer",
                            Province = "Ho Chi Minh"
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CandidateToCompanyRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyProfileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CandidateToCompanyRequests");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Certificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CertificateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Month")
                        .HasColumnType("datetime2");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("CertificateId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CompanyProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyProfileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLogoLgr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlCompanyLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("IndustryId");

                    b.ToTable("CompanyProfile");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            CompanyName = "Tech Corp",
                            CompanyProfileDescription = "A leading tech company specializing in software solutions.",
                            Contact = "contact@techcorp.com",
                            ImageLogoLgr = "https://res.cloudinary.com/dzf0ccons/image/upload/v1748267504/image_user/bfltymsad63wfkyp3bvl.jpg",
                            IndustryId = 1,
                            IsActive = true,
                            IsVerified = true,
                            Location = "123 Tech Street, District 1, Ho Chi Minh City",
                            TeamSize = "50-100 employees",
                            UrlCompanyLogo = "https://res.cloudinary.com/dzf0ccons/image/upload/v1748267504/image_user/bfltymsad63wfkyp3bvl.jpg",
                            Website = "https://techcorp.com"
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsStudying")
                        .HasColumnType("bit");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MonthEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MonthStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YearEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YearStart")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Embedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Embeddings");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExperienceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9228),
                            ExperienceName = "Less than 1 year",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9229),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9231),
                            ExperienceName = "1-3 years",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9231),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9233),
                            ExperienceName = "More than 3 years",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9233),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.ExperienceLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ExperienceLevel");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Fresher"
                        },
                        new
                        {
                            id = 2,
                            name = "Junior"
                        },
                        new
                        {
                            id = 3,
                            name = "Middle"
                        },
                        new
                        {
                            id = 4,
                            name = "Senior"
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.ForeignLanguage", b =>
                {
                    b.Property<int>("ForeignLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForeignLanguageId"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LanguageLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ForeignLanguageId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("ForeignLanguages");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.HighlightProject", b =>
                {
                    b.Property<int>("HighlightProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HighlightProjectId"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MonthEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MonthStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YearEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YearStart")
                        .HasColumnType("datetime2");

                    b.HasKey("HighlightProjectId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("HighlightProjects");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Industry", b =>
                {
                    b.Property<int>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndustryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IndustryId");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            IndustryId = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9263),
                            IndustryName = "Information Technology",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9264)
                        },
                        new
                        {
                            IndustryId = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9266),
                            IndustryName = "Finance",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9266)
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeactivatedByAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DescriptionWeight")
                        .HasColumnType("real");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("EducationWeight")
                        .HasColumnType("real");

                    b.Property<int>("ExperienceLevelId")
                        .HasColumnType("int");

                    b.Property<float>("ExperienceWeight")
                        .HasColumnType("real");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSalaryNegotiable")
                        .HasColumnType("bit");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSalary")
                        .HasColumnType("int");

                    b.Property<int?>("MinSalary")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SkillsWeight")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YourExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YourSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExperienceLevelId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("LevelId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            AddressDetail = "123 Tech Street, District 1",
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9428),
                            DeactivatedByAdmin = false,
                            Description = "Develop and maintain web applications using C# and JavaScript.",
                            DescriptionWeight = 0f,
                            Education = "Bachelor's Degree in Computer Science",
                            EducationWeight = 0f,
                            ExperienceLevelId = 2,
                            ExperienceWeight = 0f,
                            ExpiryDate = new DateTime(2025, 7, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9419),
                            IndustryId = 1,
                            IsSalaryNegotiable = true,
                            JobTypeId = 1,
                            LevelId = 2,
                            MaxSalary = 55000,
                            MinSalary = 45000,
                            ProvinceName = "Ho Chi Minh City",
                            SkillsWeight = 0f,
                            Status = 1,
                            TimeEnd = new DateTime(2025, 7, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9426),
                            TimeStart = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9426),
                            Title = "Junior Software Engineer",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9428),
                            YourExperience = "1+ years working with web development",
                            YourSkill = "C#, .NET, JavaScript, SQL"
                        },
                        new
                        {
                            JobId = 2,
                            AddressDetail = "456 Finance Avenue, Ba Dinh",
                            CompanyId = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9435),
                            DeactivatedByAdmin = false,
                            Description = "Analyze financial data and generate reports.",
                            DescriptionWeight = 0f,
                            Education = "Master's Degree in Finance or Data Science",
                            EducationWeight = 0f,
                            ExperienceLevelId = 4,
                            ExperienceWeight = 0f,
                            ExpiryDate = new DateTime(2025, 8, 7, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9432),
                            IndustryId = 2,
                            IsSalaryNegotiable = false,
                            JobTypeId = 3,
                            LevelId = 3,
                            MaxSalary = 85000,
                            MinSalary = 75000,
                            ProvinceName = "Hanoi",
                            SkillsWeight = 0f,
                            Status = 0,
                            TimeEnd = new DateTime(2025, 8, 7, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9433),
                            TimeStart = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9433),
                            Title = "Senior Data Analyst",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9435),
                            YourExperience = "5+ years of data analysis experience",
                            YourSkill = "SQL, Python, Excel, Power BI"
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9291),
                            JobTypeName = "Full-time",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9292)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9294),
                            JobTypeName = "Part-time",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9294)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9296),
                            JobTypeName = "Remote",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9296)
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9321),
                            LevelName = "Intern",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9321)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9323),
                            LevelName = "Junior",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9323)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9325),
                            LevelName = "Senior",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9325)
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9078),
                            RoleName = "Candidate",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9081)
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9090),
                            RoleName = "Company",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9091)
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9092),
                            RoleName = "Admin",
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9092)
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SkillId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9466),
                            Email = "tinhadmin@gmail.com",
                            FullName = "tinh",
                            IsActive = true,
                            Password = "123",
                            Phone = "0123456789",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9467)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9471),
                            Email = "contact@techcorp.com",
                            FullName = "Tech Corp",
                            IsActive = true,
                            Password = "123",
                            Phone = "0987654321",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9471)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9474),
                            Email = "admin@jobfinder.com",
                            FullName = "Admin User",
                            IsActive = true,
                            Password = "123",
                            Phone = "0912345678",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2025, 6, 23, 2, 52, 28, 992, DateTimeKind.Utc).AddTicks(9474)
                        });
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.UserFavoriteCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavoriteCompanies");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.UserFavoriteJob", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("UserFavoriteJobs");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.WorkExperience", b =>
                {
                    b.Property<int>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkExperienceId"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MonthEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MonthStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProJects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("YearEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YearStart")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.AboutMe", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("AboutMes")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Application", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CV", "CV")
                        .WithMany("Applications")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Applications_CVs_UniqueCvId");

                    b.HasOne("JOB_FINDER_API.Models.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CV");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Award", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Awards")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CV", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithMany("CVs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CandidateProfile", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("JOB_FINDER_API.Models.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Certificate", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Certificates")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CompanyProfile", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithOne("CompanyProfile")
                        .HasForeignKey("JOB_FINDER_API.Models.CompanyProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Contact", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Education", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Experience", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.ForeignLanguage", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("ForeginLanguages")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.HighlightProject", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("HighlightProjects")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Job", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "Company")
                        .WithMany("PostedJobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.ExperienceLevel", "ExperienceLevel")
                        .WithMany("Jobs")
                        .HasForeignKey("ExperienceLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.Industry", "Industry")
                        .WithMany("Jobs")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.JobType", "JobType")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.Level", "Level")
                        .WithMany("Jobs")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ExperienceLevel");

                    b.Navigation("Industry");

                    b.Navigation("JobType");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.JobSkill", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Message", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Skill", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.User", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.UserFavoriteCompany", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.User", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithMany("FavoriteCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.UserFavoriteJob", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.Job", "Job")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JOB_FINDER_API.Models.User", "User")
                        .WithMany("FavoriteJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.WorkExperience", b =>
                {
                    b.HasOne("JOB_FINDER_API.Models.CandidateProfile", "CandidateProfile")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CV", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.CandidateProfile", b =>
                {
                    b.Navigation("AboutMes");

                    b.Navigation("Awards");

                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("ForeginLanguages");

                    b.Navigation("HighlightProjects");

                    b.Navigation("Skills");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.ExperienceLevel", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Industry", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("FavoritedByUsers");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.JobType", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Level", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("JOB_FINDER_API.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CVs");

                    b.Navigation("CandidateProfile");

                    b.Navigation("CompanyProfile");

                    b.Navigation("Contacts");

                    b.Navigation("Experiences");

                    b.Navigation("FavoriteCompanies");

                    b.Navigation("FavoriteJobs");

                    b.Navigation("PostedJobs");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
